# Generated by Django 3.0.3 on 2022-01-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='replied',
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(verbose_name='教學計劃'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上傳時間'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.CharField(max_length=30, verbose_name='科目'),
        ),
    ]
