# Generated by Django 3.0.3 on 2022-01-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20220108_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.IntegerField(choices=[(0, '未分類'), (1, '數學'), (2, '國文'), (3, '英文'), (4, '歷史'), (5, '地理'), (6, '公民'), (7, '物理'), (8, '化學'), (9, '生物'), (10, '音樂'), (11, '美術'), (12, '國防教育'), (13, '健護'), (99, '體育')], default=0, verbose_name='科目'),
        ),
    ]
