# Generated by Django 3.0.3 on 2022-01-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20220108_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='classes',
            field=models.IntegerField(choices=[(0, '未選擇'), (1, '101'), (2, '102'), (3, '103'), (4, '104'), (5, '105'), (6, '106'), (7, '107'), (8, '108'), (9, '109'), (10, '110'), (11, '201'), (12, '202'), (13, '203'), (14, '204'), (15, '205'), (16, '206'), (17, '207'), (18, '208'), (19, '209'), (20, '210'), (21, '301'), (22, '302'), (23, '303'), (24, '304'), (25, '305'), (26, '306'), (27, '307'), (28, '308'), (29, '309'), (30, '310')], default=0, verbose_name='班級'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.IntegerField(choices=[(0, '未選擇'), (1, '數學'), (2, '國文'), (3, '英文'), (4, '歷史'), (5, '地理'), (6, '公民'), (7, '物理'), (8, '化學'), (9, '生物'), (10, '音樂'), (11, '美術'), (12, '國防教育'), (13, '健護'), (99, '體育')], default=0, verbose_name='科目'),
        ),
    ]
