# Generated by Django 3.1.4 on 2022-06-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20220108_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='author',
        ),
        migrations.AlterField(
            model_name='topic',
            name='classes',
            field=models.IntegerField(choices=[(0, '未選擇'), (1, '高中'), (2, '高職'), (3, '五專')], default=0, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(verbose_name='內容'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='subject',
            field=models.IntegerField(choices=[(0, '未選擇'), (1, '公立'), (2, '私立')], default=0, verbose_name='公/私立'),
        ),
    ]
