# Generated by Django 3.1.4 on 2022-06-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0005_auto_20220618_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(verbose_name='學校名稱'),
        ),
    ]
