# Generated by Django 3.1.4 on 2022-06-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0007_topic_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.CharField(max_length=256, verbose_name='學校名稱'),
        ),
    ]
