# Generated by Django 3.1.4 on 2022-06-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0008_auto_20220618_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='road',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='入學方法'),
        ),
    ]
