# Generated by Django 3.1.4 on 2022-06-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0011_auto_20220619_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slink1',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='學校官網'),
        ),
        migrations.AddField(
            model_name='topic',
            name='slink2',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='招生參考網址'),
        ),
    ]
